# Generated by Django 5.0.3 on 2024-03-15 00:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Income',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kategori', models.CharField(max_length=255)),
                ('jumlah', models.CharField(max_length=255)),
                ('keterangan', models.CharField(max_length=255)),
                ('tanggal', models.DateField()),
            ],
        ),
    ]
