# Generated by Django 5.0.3 on 2024-03-27 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('income', '0003_reference'),
    ]

    operations = [
        migrations.CreateModel(
            name='Need',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=255)),
                ('quantity', models.CharField(max_length=50)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('status', models.IntegerField(default=1)),
            ],
        ),
        migrations.AddField(
            model_name='reference',
            name='harga',
            field=models.CharField(default=0, max_length=255),
        ),
    ]
